name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        uses: actions/setup-node@v4

      - run: npm install

      - name: Set NODE_ENV to production
        run: echo "NODE_ENV=production" >> "$GITHUB_OUTPUT"

      - run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: public
          folder: out
